spring:
  redis:
    host: 192.168.1.100
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: true
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
