spring:
  redis:
    host: 192.168.1.100
    port: 6379
  task:
    #异步任务加定时任务
    execution:
      pool:
        max-size: 50
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    host: 192.168.1.100
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual